baseURL = "https://crisbh.github.io/foundations-numerical-relativity-talk/"
languageCode = "es"
title = "Charla - Fundamentos de la Relatividad NumÃ©rica"
theme = "book"
enableEmoji = true

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSearch = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokailight'
    tabWidth = 8

[[menu.after]]
    name = "ðŸ“– Charla"
    url = "/slides/"
    weight = 5

